config/routes.rb
Rails.application.routes.draw do
  root to: 'admin#index'
  resources :films
  resources :genres
  resources :directors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :films
  validates :name, presence: true, uniqueness: true
  validates :nationality, presence: true
  validates :date_of_birth, presence: true
  validates :favorite_genre, presence: true
end

app/models/film.rb
class Film < ApplicationRecord
  has_one_attached :poster, dependent: :purge
  belongs_to :director
  belongs_to :genre

  validates :title, presence: true
  validates :release_year, presence: true
  validates :synopsis, presence: true
  validates :country_of_origin, presence: true
  validates :duration, presence: true
  validates :released, inclusion: { in: [true, false]}
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :films
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all
  end

  def show
    @director = Director.find(params[:id])
  end

  def new
  end

  def create
    # director has the fields name, nationality, date_of_birth, favorite_genre
    @director = Director.new(params.require(:director).permit(:name, :nationality, :date_of_birth, :favorite_genre))
    # check if director already exists
    if Director.exists?(name: @director.name)
      flash[:notice] = "Director already exists!"
      redirect_to new_director_path
    else
      @director.save
      redirect_to directors_path
    end
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])
    @director.update(params.require(:director).permit(:name, :nationality, :date_of_birth, :favorite_genre))
    redirect_to director_path(@director)
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    if params[:genre_id].present?
      @filter_name = Genre.find(params[:genre_id]).name
      @films = Film.where(genre_id: params[:genre_id])
    elsif params[:director_id].present?
      @filter_name = Director.find(params[:director_id]).name
      @films = Film.where(director_id: params[:director_id])
    else
      @films = Film.all
   end
  end

  def show
    @film = Film.find(params[:id])
  end

  def new
  end

  def create
    @film = Film.new(params.require(:film).permit(:title, :release_year, :synopsis, :country_of_origin, :duration, :released, :director_id, :genre_id, :poster))
    if @film.save
      redirect_to films_path
    else
      flash[:notice] = "All parameters must be filled in!"
      redirect_to new_film_path
    end
  end

  def edit
    @film = Film.find(params[:id])
  end

  def update
    @film = Film.find(params[:id])
    @film.update(params.require(:film).permit(:title, :release_year, :synopsis, :country_of_origin, :duration, :released, :director_id, :genre_id, :poster))
    redirect_to film_path(@film)
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy
    redirect_to films_path
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
  end

  def create
    @genre = Genre.new(params.require(:genre).permit(:name))
    # check if genre already exists
    if Genre.exists?(name: @genre.name)
      flash[:notice] = "Genre already exists!"
      redirect_to new_genre_path
    else
      @genre.save
      redirect_to genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(params.require(:genre).permit(:name))
    redirect_to genres_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admin/index.html.erb
<div class="flex flex-col gap-4 justify-center items-center">
  <h1 class="text-3xl font-bold uppercase">Film Catalog - Dashboard</h1>
  <div class="bg-[#1B141D] rounded-lg p-4 w-full">
    <h2 class="text-2xl font-bold">Filmes</h2>
    <div class="flex gap-8">
      <%= link_to 'Ver todos os filmes', films_path, class: "text-blue-500" %>
      <%= link_to 'Adicionar novo filme', new_film_path, class: "text-blue-500" %>
    </div>
  </div>
  <div class="bg-[#1B141D] rounded-lg p-4 w-full">
    <h2 class="text-2xl font-bold">Gêneros</h2>
    <div class="flex gap-8">
      <%= link_to 'Ver todos os gêneros', genres_path, class: "text-blue-500" %>
      <%= link_to 'Adicionar novo gênero', new_genre_path, class: "text-blue-500" %>
    </div>
  </div>
  <div class="bg-[#1B141D] rounded-lg p-4 w-full">
    <h2 class="text-2xl font-bold">Diretores</h2>
    <div class="flex gap-8">
      <%= link_to 'Ver todos os diretores', directors_path, class: "text-blue-500" %>
      <%= link_to 'Adicionar novo diretor', new_director_path, class: "text-blue-500" %>
    </div>
  </div>
</div>

app/views/directors/edit.html.erb
<div class="flex flex-col justify-between items-center">
  <h1 class="text-3xl font-bold">New Director</h1>
  <%= form_for @director do |form| %>
    <div class="flex flex-col space-y-4 text-black">
      <div class="flex flex-col space-y-2">
        <%= form.label :name, class: "text-white text-lg font-semibold" %>
        <%= form.text_field :name, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :nationality, class: "text-white text-lg font-semibold" %>
        <%= form.text_field :nationality, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :date_of_birth, class: "text-white text-lg font-semibold" %>
        <%= form.date_field :date_of_birth, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div> 
        <%= form.label :favorite_genre, class: "text-white text-lg font-semibold" %>
        <%= form.collection_select :favorite_genre, Genre.all, :id, :name, { prompt: "Select a favorite genre" }, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex justify-center gap-8">
        <%= link_to 'Back', root_path, class: "p-2 text-black bg-gray-300 rounded-md" %>
        <%= form.submit "Create Director", class: "p-2 bg-blue-500 text-white rounded-md cursor-pointer" %>
      </div>
    </div>
  <% end %>
</div>

app/views/directors/index.html.erb
<div class="flex flex-col gap-10">
  <div>
    <% @directors.each do |director| %>
      <ul class="flex flex-col my-4">
        <li><%= director.name %></li>
      </ul>
      <div class="flex flex-row gap-4">
        <%= link_to 'Films with this director', films_path(director_id: director.id), class: "text-yellow-500 hover:text-yellow-200 bg-[#1B141D] p-2 rounded-lg" %>
        <%= link_to "Edit information", edit_director_path(director), class: "text-yellow-500 hover:text-yellow-200 bg-[#1B141D] p-2 rounded-lg" %>
      </div>
    <% end %>
  </div>
  <div class="flex justify-center">
    <%= link_to 'Back', root_path, class: "p-2 text-black bg-gray-300 rounded-md" %>
  </div>
</div>

app/views/directors/new.html.erb
<% if flash.any? %>
 <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold"><%= name.capitalize %>:</strong>
      <span class="block sm:inline"><%= msg %></span>
    </div>
 <% end %>
<% end %>

<div class="flex flex-col justify-between items-center">
  <h1 class="text-3xl font-bold">New Director</h1>
  <%= form_for Director.new do |form| %>
    <div class="flex flex-col space-y-4 text-black">
      <div class="flex flex-col space-y-2">
        <%= form.label :name, class: "text-white text-lg font-semibold" %>
        <%= form.text_field :name, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :nationality, class: "text-white text-lg font-semibold" %>
        <%= form.text_field :nationality, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :date_of_birth, class: "text-white text-lg font-semibold" %>
        <%= form.date_field :date_of_birth, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div> 
        <%= form.label :favorite_genre, class: "text-white text-lg font-semibold" %>
        <%= form.collection_select :favorite_genre, Genre.all, :id, :name, { prompt: "None" }, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex justify-center gap-8">
        <%= link_to 'Back', root_path, class: "p-2 bg-gray-300 rounded-md" %>
        <%= form.submit "Create Director", class: "p-2 bg-blue-500 text-white rounded-md cursor-pointer" %>
      </div>
    </div>
  <% end %>
</div>

app/views/films/edit.html.erb
<div class="flex flex-col justify-between items-center">
  <h1 class="text-3xl font-bold">Edit Film - <%= @film.title %></h1>
  <%= form_for @film do |form| %>
    <div class="flex flex-col space-y-4 text-black">
      <div class="flex flex-col space-y-2">
        <%= form.label :title, class: "text-white text-lg font-semibold" %>
        <%= form.text_field :title, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :release_year, class: "text-white text-lg font-semibold" %>
        <%= form.number_field :release_year, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :synopsis, class: "text-white text-lg font-semibold" %>
        <%= form.text_area :synopsis, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :country_of_origin, class: "text-white text-lg font-semibold" %>
        <%= form.text_field :country_of_origin, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :duration, class: "text-white text-lg font-semibold" %>
        <%= form.number_field :duration, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :director, class: "text-white text-lg font-semibold" %>
        <%= form.collection_select :director_id, Director.all, :id, :name, { prompt: "Select a director" }, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :genre_id, class: "text-white text-lg font-semibold" %>
        <%= form.collection_select :genre_id, Genre.all, :id, :name, { prompt: "Select a genre" }, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex justify-center gap-4">
        <%= form.submit "Confirm Changes", class: "p-2 bg-blue-500 text-white rounded-md cursor-pointer" %>
        <%= link_to 'Back', film_path(@film), class: "p-2 bg-gray-300 rounded-md" %>
      </div>
    </div>
  <% end %>
</div>

app/views/films/index.html.erb
<div class="flex flex-col justify-center items-start gap-10">
  <div class="flex flex-row gap-8">
    <% if @filter_name.present? %>
      <h1 class="text-3xl font-bold">Films - <%= @filter_name %></h1>
    <% else %>
      <h1 class="text-3xl font-bold">Films</h1>
    <% end %>
    <%= link_to 'Back', root_path, class: "flex justify-center items-center text-center p-2 text-black bg-gray-300 rounded-xl font-bold" %>
  </div>
  <div class="flex flex-col gap-10">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5 gap-4 bg-[#372B3A] p-4 rounded-xl">
      <% @films.each do |film| %>
        <ul class="flex flex-col my-4">
          <li class="text-2xl font-bold"><%= film.title %></li>
          <% if film.released? %>
            <li><%= film.release_year %></li>
          <% else %>
            <li>Release Forecast: <%= film.release_year %></li>
          <% end %>
          <% if film.poster.attached? %>
            <%= image_tag url_for(film.poster), alt: film.title, class: "max-w-[300px] max-h-[360px]" %>
          <% else %>
            <img src="/images/no-poster-available.jpg" alt="No poster available" class="max-w-[300px] max-h-[360px]">
          <% end %>
          <%= link_to 'See details', film, class: "text-center text-yellow-500 font-bold text-xl w-full uppercase bg-[#1B141D] p-4" %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/films/new.html.erb
<% if flash.any? %>
 <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold"><%= name.capitalize %>:</strong>
      <span class="block sm:inline"><%= msg %></span>
    </div>
 <% end %>
<% end %>

<div class="flex flex-col justify-between items-center">
  <h1 class="text-3xl font-bold">New Film</h1>
  <%= form_for Film.new do |form| %>
    <div class="flex flex-col space-y-4 text-black">
      <div class="flex flex-col space-y-2">
        <%= form.label :title, class: "text-white text-lg font-semibold" %>
        <%= form.text_field :title, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :release_year, class: "text-white text-lg font-semibold" %>
        <%= form.number_field :release_year, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :synopsis, class: "text-white text-lg font-semibold" %>
        <%= form.text_area :synopsis, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :country_of_origin, class: "text-white text-lg font-semibold" %>
        <%= form.text_field :country_of_origin, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :duration, class: "text-white text-lg font-semibold" %>
        <%= form.number_field :duration, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :released, "Released", class: "text-white text-lg font-semibold" %>
        <%= form.select :released, [['Yes', true], ['No', false]], {}, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :poster, "Poster Image", class: "text-white text-lg font-semibold" %>
        <%= form.file_field :poster, class: "text-white p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :director, class: "text-white text-lg font-semibold" %>
        <%= form.collection_select :director_id, Director.all, :id, :name, { prompt: "Select a director" }, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :genre, class: "text-white text-lg font-semibold" %>
        <%= form.collection_select :genre_id, Genre.all, :id, :name, { prompt: "Select a genre" }, class: "p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex justify-center gap-8">
        <%= link_to 'Back', root_path, class: "p-2 text-black bg-gray-300 rounded-md" %>
        <%= form.submit "Create Film", class: "p-2 bg-blue-500 text-white rounded-md cursor-pointer" %>
      </div>
    </div>
  <% end %>
</div>

app/views/films/show.html.erb
<div class="flex flex-col gap-8">
  <h1 class="text-5xl font-bold"><%= @film.title %></h1>
  <div class="flex flex-col sm:flex-row">
    <% if @film.poster.attached? %>
      <%= image_tag url_for(@film.poster), alt: @film.title, class: "max-w-[300px] max-h-[360px]" %>
    <% else %>
      <img src="/images/no-poster-available.jpg" alt="No poster available" class="max-w-[300px] max-h-[360px]">
    <% end %>
    <ul class="flex flex-col m-4 gap-2 text-xl">
      <% if film.released? %>
        <li class="text-3xl"><%= @film.release_year %></li>
      <% else %>
        <li class="text-3xl">Release Forecast: <%= @film.release_year %></li>
      <% end %>
      <li class="max-w-[450px] break-words"><%= @film.synopsis %></li>
      <li><%= @film.country_of_origin %></li>
      <li><%= @film.duration %> min</li>
      <li><%= @film.director.name %></li>
      <li><%= @film.genre.name %></li>
    </ul>
  </div>
  <div class="flex flex-row gap-4">
    <%= link_to 'Edit', edit_film_path(@film), class: "text-red-500 text-lg bg-[#1B141D] p-2 rounded-xl" %>
    <%= button_to 'Delete', @film, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "text-red-500 text-lg bg-[#1B141D] p-2 rounded-xl" %>
    <%= link_to 'Back', films_path, class: "text-black bg-gray-300 p-2 rounded-xl" %>
  </div>
</div>

app/views/genres/edit.html.erb
<div class="flex flex-col justify-between items-center">
  <h1 class="text-3xl font-bold">Edit Genre</h1>
  <%= form_for @genre do |form| %>
    <div class="flex flex-col space-y-4">
      <div class="flex flex-col space-y-2">
        <%= form.label :name, class: "text-lg font-semibold" %>
        <%= form.text_field :name, class: "text-black p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex justify-center gap-8">
        <%= link_to 'Back', genres_path, class: "p-2 text-black bg-gray-300 rounded-md" %>
        <%= form.submit "Confirm Changes", class: "p-2 bg-blue-500 text-white rounded-md cursor-pointer" %>
      </div>
    </div>
  <% end %>
</div>

app/views/genres/index.html.erb
<div class="flex flex-col gap-10">
  <div>
    <% @genres.each do |genre| %>
      <ul class="flex flex-col my-4">
        <li class="text-2xl"><%= genre.name %></li>
      </ul>
      <div class="flex flex-row gap-4">
        <%= link_to 'Films with this genre', films_path(genre_id: genre.id), class: "text-yellow-500 hover:text-yellow-200 bg-[#1B141D] p-2 rounded-lg" %>
        <%= link_to "Edit name", edit_genre_path(genre), class: "text-yellow-500 hover:text-yellow-200 bg-[#1B141D] p-2 rounded-lg" %>
      </div>
    <% end %>
  </div>
  <div class="flex justify-center">
    <%= link_to 'Back', root_path, class: "p-2 text-black bg-gray-300 rounded-md" %>
  </div>
</div>

app/views/genres/new.html.erb
<% if flash.any? %>
 <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold"><%= name.capitalize %>:</strong>
      <span class="block sm:inline"><%= msg %></span>
    </div>
 <% end %>
<% end %>

<div class="flex flex-col justify-between items-center">
  <h1 class="text-3xl font-bold mb-2">New Genre</h1>
  <%= form_for Genre.new do |form| %>
    <div class="flex flex-col space-y-4">
      <div class="flex flex-col space-y-2">
        <%= form.label :name, class: "text-lg font-semibold" %>
        <%= form.text_field :name, class: "text-black p-2 border border-gray-300 rounded-md" %>
      </div>
      <div class="flex justify-center gap-8">
        <%= link_to 'Back', root_path, class: "p-2 text-black bg-gray-300 rounded-md" %>
        <%= form.submit "Create Genre", class: "p-2 bg-blue-500 text-white rounded-md cursor-pointer" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>FilmCatalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-[#120B13]">
    <main class="flex flex-col p-8 justify-center items-center text-white">
      <%= yield %>
    </main>
  </body>
</html>